config = {
    "ONEM2M_SERVER": "http://127.0.0.1:5089",
    "CSE": "/~/in-cse/in-name/",
    "SUBSCRIBE_LINK": "http://localhost:5000/data",
    "kafka_platform_ip": "20.2.81.4:19092",
    "kafka_platform_ip_": "localhost:9092",
    "kafkaIp": "20.2.81.4",
    "kafkaPortNo": "19092",
    "database": "platform",
    "registry": "app_service_sensor",
    "topics": "user_topics",
    "meta_data": "meta",
    "config_file": "sensor_config.json",
    "min_dis": "10",
    "mongouri": "mongodb+srv://admin:iasproject@cluster0.t5qnsna.mongodb.net/",
    "sensors_url_": "https://iudx-rs-onem2m.iiit.ac.in/resource/sensors",
    "nodes_url_": "https://iudx-rs-onem2m.iiit.ac.in/resource/nodes/",
    "data_channels_": "https://iudx-rs-onem2m.iiit.ac.in/channels/",
    "descriptor_url_": "https://iudx-rs-onem2m.iiit.ac.in/resource/descriptor/",
    "sensors_url": "http://localhost:5001/get_sensors",
    "nodes_url": "http://localhost:5001/get_nodes",
    "data_channels": "http://localhost:5001/channels/",
    "descriptor_url": "http://localhost:5001/get_sensor_description"
}